apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      model: calc
  template:
    metadata:
      labels:
        model: calc
    spec:
      containers:
        - name: calculator
          image: fbaensch/calculator_test:latest
          env:
            - name: OUTPUT_PATH
              value: output
          volumeMounts:
            - mountPath: /app/output
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc